### ISSUE TITLE
Update ASP.NET Core streaming sample

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#106]
[ASP.NET Core streaming sample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/streaming)  to be cross platform.  See [this comment](https://github.com/dotnet/AspNetCore.Docs.Samples/pull/86#issuecomment-1275401378)

@logiclrd do you have an ETA for that?

**Comment by logiclrd** [comment]
I don't know. The project owner accepted my change pretty quickly but then hasn't actually published any new version. It's disappointing but it may make sense to just proceed with what we've got after all.

**Comment by Rick-Anderson** [comment]
@logiclrd 
> I don't know. The project owner accepted my change pretty quickly but then hasn't actually published any new version. It's disappointing but it may make sense to just proceed with what we've got after all.

Can you provide a link, I could ask when he plans on publishing the PR's he's accepted.

**Comment by logiclrd** [comment]
Here's the project:

https://github.com/mrousavy/AnimatedGif

Here's the PR that has been merged in but not yet released:

https://github.com/mrousavy/AnimatedGif/pull/19

Here's the package on nuget.org:

https://www.nuget.org/packages/AnimatedGif

Version 1.0.5 was released in June 2019, and my PR is the only one that has altered the code since then.

Thanks :-)

**Comment by Rick-Anderson** [comment]
@logiclrd I sent him a message, hopefully he'll publish soon.
