### ISSUE TITLE
 IProblemDetailsService.WriteAsync with API controller 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#60]
See the [middleware version](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/problem-details-service/Program.cs#L77=L129)

`/api/values/Squareroot/-1`  returns the generic type and title
`{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request",`
not the type and title that's set
`{"type":"https://en.wikipedia.org/wiki/Square_root","title":"Wrong Input"`

When I [Customize problem details with CustomizeProblemDetails]( https://review.learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0&branch=pr-en-us-27009#customize-problem-details-with-customizeproblemdetails) see also [source code](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/problem-details-service/Program.cs#L163-L191)

the API controller returns the correct problem details.

When I step through the middleware version in the debugger, everything is set correctly.

@sammychinedu2ky

**Comment by sammychinedu2ky** [comment]
Ok let me check it out

**Comment by sammychinedu2ky** [comment]
The middleware and controller version seems to work well from my end version seems to work for me from my end @Rick-Anderson 
Maybe you need to refresh your Swagger UI if that is what you are using

**Comment by sammychinedu2ky** [comment]
Ooh sorry I'm mistaken, seems the controller was activated for the middleware as well

**Comment by Rick-Anderson** [comment]
> Maybe you need to refresh your Swagger UI

Speaking of Swagger, maybe we should remove Swagger since it's not needed for the sample.

**Comment by sammychinedu2ky** [comment]
> > Maybe you need to refresh your Swagger UI
> 
> Speaking of Swagger, maybe we should remove Swagger since it's not needed for the sample.

I'm still trying to figure out why the minimal API is working but the controller isn't.

**Comment by Rick-Anderson** [comment]
The controller works with `CustomizeProblemDetails` 
Build with `#define API_CONTROLLER` and test the controller.

**Comment by sammychinedu2ky** [comment]
Yh I tried that and it worked

**Comment by Rick-Anderson** [comment]
@brunolins16 can you help with this mystery?  When using middleware, API controller problem details are overwritten. 
When we [Customize problem details with CustomizeProblemDetails]( https://review.learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0&branch=pr-en-us-27009#customize-problem-details-with-customizeproblemdetails) see also [source code](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/problem-details-service/Program.cs#L163-L191)

the API controller returns the correct problem details.

**Comment by brunolins16** [comment]
Let me check if I understand the issue:

1. **Middleware version**: the produced `ProblemDetails` is not what you are expecting.
2. **CustomizeProblemDetails version**: the `ProblemDetails` is update with the expected message

If that is the question I can explain:

In the middleware version you are calling the `ProblemDetailsService.WriteAsync` that has some conditions to work 

https://github.com/dotnet/aspnetcore/blob/ce2db7ea0b161fc5eb35710fca6feeafeeac37bc/src/Http/Http.Extensions/src/ProblemDetailsService.cs#L24

As you can see it will be a no-op when the `HttpResponse.Body` already started that is the case since the API controller produced the PD and started writing to the `HttpResponse.Body`, so, in this case it is too late. If we don't want to auto-generate problem details in this scenario you will need to disable it [Disable ProblemDetails response](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-7.0#disable-problemdetails-response-1) and it might work as expected.

However, when using the `CustomizeProblemDetails` the customization delegate will be called when the API Controller ProblemDetails is generated, before writing to the `HttpResponse.Body`, and in this case we are actually not calling  `ProblemDetailsService.WriteAsync`.

https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L101

**Comment by Rick-Anderson** [comment]
@brunolins16 awesome. I think I'll explain what's going on in the article. Customers will hit this. I forgot about `HttpResponse.Body ` already started and customers will too.
I think I'll also remove Swagger since it's not needed for Problem details unless you think I should keep it.

**Comment by brunolins16** [comment]
I think I will update the API comments here (https://github.com/dotnet/aspnetcore/blob/ce2db7ea0b161fc5eb35710fca6feeafeeac37bc/src/Http/Http.Abstractions/src/ProblemDetails/IProblemDetailsService.cs#L22) to explicitly call out it as well.

**Comment by Rick-Anderson** [comment]
> update the API comments here
Agreed.

Should I remove Swagger from the sample code to simplify it?

**Comment by sammychinedu2ky** [comment]
Thanks @brunolins16 makes, that makes sense 😅

**Comment by sammychinedu2ky** [comment]
Suppressing the automatic generation of problem details still returns a 400 status code for bad requests

![image](https://user-images.githubusercontent.com/36219292/191386352-9b34b865-a101-479d-ab2f-7b5aa85aa858.png)

![image](https://user-images.githubusercontent.com/36219292/191386431-12aca65e-e0fb-4810-bf5e-5157f72144ad.png)

**Comment by sammychinedu2ky** [comment]
@brunolins16  @Rick-Anderson

**Comment by Rick-Anderson** [comment]
> Suppressing the automatic generation of problem details still returns a 400 status code for bad requests

Yes, `SuppressMapClientErrors` does is change it from
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "Bad Request",
  "status": 400,
  "traceId": "00-cbbbc183cb1e5842d897dec37ca2fbd7-717b080cf65f6068-00"
}
```
to
```
Status Code: 400; Bad Request    
```

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky So I can't get your custom PD response from an API controller. I thought I was getting custom PD responses from the API controller before but may I didn't look carefully at the response. It seems there's no way to get a  custom PD responses from an API controller.

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  it's working, I had two different API controllers.

**Comment by sammychinedu2ky** [comment]
Two different API controllers ... how please?

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
> Two different API controllers ... how please?

You'll see tonight when I build you a version of the article.

**Comment by sammychinedu2ky** [comment]
> > Two different API controllers ... how please?
> 
> You'll see tonight when I build you a version of the article.

Alright would be expecting to see . Thanks 😅
